pool:
  name: 'SelfHosted'
trigger:
  - develop 
variables:
  appServiceCodeName: $(appServiceCodeName)
  resourceGroupName: $(resourceGroupName)
jobs:
  - job: Front
    variables:
      - group: 'tpfinal-vars'
    steps:
      - template: .azure/pipelines/templates/_build-front.yml
        
        
          